package("juce")
    set_kind("library", {headeronly = true})
    set_homepage("https://juce.com/")
    set_description("JUCE audio application framework modules")
    set_license("AGPL-3.0-or-later OR commercial")
    add_urls("https://github.com/juce-framework/JUCE/archive/refs/tags/$(version).tar.gz")
    add_versions("8.0.12", "dec1a8baee5aaec4502b717a421b850e257ab7e9c2efd03766185ec1957cf102")
    add_includedirs("modules")
    add_includedirs("modules/juce_audio_plugin_client/AU")
    add_includedirs("modules/juce_audio_processors_headless/format_types/VST3_SDK")

    on_install(function (package)
        os.cp("modules", package:installdir())
        os.cp("LICENSE.md", package:installdir("share/licenses/JUCE/LICENSE.md"))
    end)
