[package]
name = "delaylama-editor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
license-file.workspace = true
description = "Source-coordinate editor interaction model for Delay Lama"
keywords.workspace = true
categories.workspace = true

[dependencies]
delaylama-synthesizer = { path = "../synthesizer" }
delaylama-editor-assets = { path = "../editor-assets" }
num-traits = { workspace = true }

[lints]
workspace = true
