use crate::types::*;
#[derive(Clone, Debug)] pub struct SynthEngine { sample_rate:f64, channels:usize, params:Parameters, voice:VoiceState, pad:PadState, bend:f32, phase:f64, delay:Vec<f32>, delay_pos:usize }
impl Default for SynthEngine {fn default()->Self{Self{sample_rate:DEFAULT_SAMPLE_RATE,channels:2,params:Parameters::default(),voice:VoiceState{current_note:-1,gate:false},pad:PadState::default(),bend:0.5,phase:0.,delay:vec![0.;44100],delay_pos:0}}}
impl SynthEngine {
 pub fn prepare(&mut self,sample_rate:f64,_max:usize,ch:usize){self.sample_rate=if sample_rate.is_finite(){sample_rate.clamp(MIN_SAMPLE_RATE,MAX_SAMPLE_RATE)}else{DEFAULT_SAMPLE_RATE};self.channels=ch.max(1);self.delay=vec![0.;(self.sample_rate*0.5) as usize];self.reset()}
 pub fn reset(&mut self){self.voice=VoiceState{current_note:-1,gate:false};self.pad=PadState::default();self.bend=0.5;self.phase=0.;self.delay.fill(0.);self.delay_pos=0}
 pub fn set_parameters(&mut self,p:Parameters){self.params=Parameters{vowel:clamp(p.vowel,0.5),port_time:clamp(p.port_time,0.5),delay_mix:clamp(p.delay_mix,0.8),voice:clamp(p.voice,0.5),vibrato:clamp(p.vibrato,0.),volume:clamp(p.volume,0.1),xy_routing:clamp(p.xy_routing,0.)}}
 pub fn parameters(&self)->Parameters{self.params} pub fn voice_state(&self)->VoiceState{self.voice} pub fn pad_state(&self)->PadState{self.pad}
 pub fn atlas_selector(&self)->f32{if self.voice.gate{0.2+0.8*self.params.vowel}else{5./30.}}
 pub fn process(&mut self,outputs:&mut [&mut [f32]],n:usize,events:&[Event]){for i in 0..n{for e in events.iter().filter(|e|e.sample_offset==i as i32 || (i==0 && e.sample_offset<0)){self.apply(*e)} let freq=if self.voice.gate{440.*2f64.powf((self.voice.current_note as f64-69.)/12.)}else{0.}; self.phase=(self.phase+freq/self.sample_rate)%1.; let dry=(self.phase*std::f64::consts::TAU).sin() as f32*self.params.volume*if self.voice.gate {1.} else {0.}; let d=self.delay[self.delay_pos]; self.delay[self.delay_pos]=dry+d*0.35; self.delay_pos=(self.delay_pos+1)%self.delay.len(); let out=dry*(1.-self.params.delay_mix)+d*self.params.delay_mix; for ch in outputs.iter_mut(){if i<ch.len(){ch[i]=out}}}}
 fn apply(&mut self,e:Event){match e.kind{EventType::NoteOn=>{if e.value>0.{self.voice=VoiceState{current_note:e.note,gate:true}}else{self.voice=VoiceState{current_note:-1,gate:false}}},EventType::NoteOff=>self.voice=VoiceState{current_note:-1,gate:false},EventType::PitchBend=>self.bend=if e.value>1.{e.value/16383.}else{e.value.clamp(0.,1.)},EventType::PadPitch=>{self.pad.pitch_modulation=clamp(e.value,0.5);self.pad.active=true},EventType::PadVowel=>{self.pad.vowel=clamp(e.value,0.5);self.pad.active=true},EventType::ControlChange=>{let v=if e.value>1.{e.value/127.}else{e.value.clamp(0.,1.)};match e.controller{1=>self.params.vibrato=v,5=>self.params.port_time=v,7=>self.params.volume=v*0.8,16=>self.params.xy_routing=v,17=>self.params.delay_mix=v,18=>self.params.voice=v,_=>{}}}}}
}
fn clamp(v:f32,f:f32)->f32{if v.is_finite(){v.clamp(0.,1.)}else{f}}
